apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-server
spec:
  project: default
  source:
    repoURL: <set-by-the-kustomize-overlay>
    targetRevision: master
    path: workload/git-server/manifests/overlays/kind
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
