apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostfs-pvc
  namespace: git-server
spec:
  volumeName: hostfs-volume
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: ""
