apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-page
spec:
  project: default
  source:
    repoURL: <set-by-the-kustomize-overlay>
    targetRevision: master
    path: workload/static-page/manifests/overlays/default
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
