apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-app-of-apps
spec:
  project: default
  source:
    repoURL: <set-by-the-kustomize-overlay>
    targetRevision: master
    path: <set-by-the-kustomize-overlay>
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
