apiVersion: v1
kind: Secret
metadata:
  name: argo-cd-apps-git-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  type: git
  url: <set-by-the-kustomize-overlay>
