apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- namespace.yaml
- ingress-nginx.yaml
patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: ingress-nginx-controller
    patch: |-
      - op: replace
        path: /data/log-format-escape-json
        value: "true"
      - op: replace
        path: /data/log-format-upstream
        # source: https://github.com/marcel-dempers/docker-development-youtube-series/blob/dc163cf341f5d68ba4d944d6bbefd8f0b1f4e703/kubernetes/ingress/controller/nginx/manifests/nginx-ingress.1.5.1.yaml#L34
        value: '{ "time": "$time_iso8601", "remote_addr": "$remote_addr", "proxy_protocol_addr": "$proxy_protocol_addr", "proxy_protocol_port": "$proxy_protocol_port", "x_forward_for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "host": "$host", "request_method": "$request_method", "request_uri": "$request_uri", "server_protocol": "$server_protocol", "status": $status, "request_time": $request_time, "request_length": $request_length, "bytes_sent": $bytes_sent, "upstream_name": "$proxy_upstream_name", "upstream_addr": "$upstream_addr", "upstream_uri": "$uri", "upstream_response_length": $upstream_response_length, "upstream_response_time": $upstream_response_time, "upstream_status": $upstream_status, "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent", "http_cookie": "$http_cookie", "http_device_id": "$http_x_device_id", "http_customer_id": "$http_x_customer_id" }'
